apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: demo-1
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICJhdXRoIjogIlZHVmhjbk10YVc1U1lXbHVPbWRvY0Y5blRubEtOV3R1VTAxbGNqYzRlRkZVU0RKNE5WUmtabGxOUTFvNWQyUXlia0ZWVTJJPSIKICAgIH0KICB9Cn0K