apiVersion: v1
clusters:
- cluster:
    server: https://rancher.test.sendo.vn/k8s/clusters/local
  name: local
contexts:
- context:
    cluster: local
    namespace: demo-1
    user: local
  name: local
current-context: local
kind: Config
preferences: {}
users:
- name: local
  user:
    token: kubeconfig-u-7jkhpxdp9x:7zn2h5mkntnptjztmlhhq88m7g7m6dtmdkpks64kkzjxzzbr5wsfqq
